
//unfortunately duplicated because spec files don't see global ts defs
export const enum TagType {
    Div,
    Span,
    Image,
    Anchor,
    Heading1,
    Heading2,
    Heading3,
    Heading4,
    Heading5,
    Heading6,
    Quote,
    Section,
    Aside,
    Paragraph,
    HorizontalRule,
    Break,
    Nav,
    OrderedList,
    UnorderedList,
    Input,
    TextInput,
    Button,
    Select,
    Radio,
    Checkbox,
    TextArea,
    TextString,
    Comment
}
